### ISSUE TITLE
[Feature]: Chat app in Enarx Keep (Rust)

### ISSUE THREAD

**Issue by nickvidal** [enarx/codex#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

**Description**: Develop a chat client using a simple custom protocol running in Enarx. The project can be done in a programming language of your choice and a reference implementation in Rust along with a common Web interface will be provided. One of the main case studies for Confidential Computing is the Signal messaging application, which offers end-to-end encryption using Intel SGX. A chat app in Enarx would be cross-platform.
**MVP**: Terminal chat client
**Stretch goal**: Connect the client to a provided Web Interface
**Language**: Rust, C, or C++
**Skills/Background**: Networking
**Mentor**: Richard, Roman
**Difficulty**: Medium/Hard

This project is part of **Semester of Code**:
https://github.com/jhu-ospo-courses/JHU-EN.601.270/tree/main/Fall_2022#enarx-projects

**Comment by rvolosatovs** [comment]
This is already implemented in #51
