### ISSUE TITLE
[Feature]: Port Rust chat client to C++

### ISSUE THREAD

**Issue by nickvidal** [enarx/codex#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Rust chat client and server were added in #51.
The chat client should be ported to C++.
Existing server can be used to test against.

This project is part of **Semester of Code**:
https://github.com/jhu-ospo-courses/JHU-EN.601.270/tree/main/Fall_2022#enarx-projects

**Comment by Subhajit767** [comment]
I want to work on this so please assign this to me

**Comment by rvolosatovs** [comment]
> I want to work on this so please assign this to me

Hi @Subhajit767 this task is already assigned, but if you're interested in contributing, perhaps you could work on porting the existing Rust chat client (https://github.com/enarx/codex/tree/main/Rust/tokio-chat-client) to other languages than C and C++?
